<html>
	<body>
		<h2 style="color:${marker.primeColor}"><b>Welcome !</b></h2>
		<h3><b>Hey ${name},</b></h3>
		<p style='padding:10px; padding-top:3px; text-align:justify;'>
            We're happy to welcome you in our world as a ${role}. !
		</p>
		<h3 style="color:${marker.primeColor}; margin-bottom:0px; padding-bottom:0px;">Regards</h3>
		<img src="${marker.logo}" style="height:30px; width:100px; margin-top:5px;">
	</body>
</html>